### ISSUE TITLE
No GDSII file in repo

### ISSUE THREAD

**Issue by galv** [tgingold/OpenTDC#1]
Hello Tristan, this is amazing.  However, I have a quotidian question.

I saw that you don't have a compress stage in the top-level Makefile. From what I've seen caravel.gds has a size of ~300MB by default. From what I can tell, the efabless requires you to upload gds/caravel.gds to the git repository. However, github has a maximum file size of 100MB. How did you manage to upload the GDSII file then? Thank you.

**Comment by tgingold** [comment]
Hi,  I have pushed the gds files (compressed so under 100MB).
